apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-realm-config.yaml
  - midpoint-resources-configmap.yaml
  - freeipa-setup-job.yaml
  - keycloak-realm-import-job.yaml
  - midpoint-resources-import-job.yaml
  - e2e-test-job.yaml
