apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stepca
spec:
  acme:
    server: https://step-ca-step-certificates.step-ca.svc.cluster.local/acme/acme/directory
    email: admin@practice.local
    privateKeySecretRef:
      name: stepca-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3ekNDQVdtZ0F3SUJBZ0lRWWE1S2FRc0FXOW9CSFpQTFJrZk51akFLQmdncWhrak9QUVFEQWpCQU1Sb3cKR0FZRFZRUUtFeEZUZEdWd0lFTmxjblJwWm1sallYUmxjekVpTUNBR0ExVUVBeE1aVTNSbGNDQkRaWEowYVdacApZMkYwWlhNZ1VtOXZkQ0JEUVRBZUZ3MHlOVEV5TWpReU16STROVGxhRncwek5URXlNakl5TXpJNE5UbGFNRUF4CkdqQVlCZ05WQkFvVEVWTjBaWEFnUTJWeWRHbG1hV05oZEdWek1TSXdJQVlEVlFRREV4bFRkR1Z3SUVObGNuUnAKWm1sallYUmxjeUJTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVGemRlRWVEQwpmcVBmcHRObVAwRVdFQmdMQmI4QmU0MnNGbXdoZk9BblRjb2xwNi9aWlFSSUtLM3I5dTJhUDhkaXhBdXN5UklnCk0weWNENW5POVhMZEZxTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFFd0hRWURWUjBPQkJZRUZKRTZOSnZzQ0xjTW5LVnlDUUhtSmo1ZWhzUkRNQW9HQ0NxR1NNNDlCQU1DQTBnQQpNRVVDSUE0VVNxcEVtK1o1Z2phdUYrclY1QWdJT2drSFo3cEhXWVVDS21yWVM2cEZBaUVBZ094cXBHMlZuRHlqCnp2TDJrRklac3ZyYmM5Zy9BeVRKK0s2V2tKOUZxREk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
