---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-password
  namespace: step-ca
type: Opaque
stringData:
  password: "StepCAPassword2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-provisioner
  namespace: step-ca
type: Opaque
stringData:
  password: "ACMEProvisioner2024!"
