apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird-dashboard
  namespace: netbird
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: stepca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbird.practice.local
      secretName: netbird-dashboard-tls
  rules:
    - host: netbird.practice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird-dashboard
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird-api
  namespace: netbird
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: stepca
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbird-api.practice.local
      secretName: netbird-api-tls
  rules:
    - host: netbird-api.practice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird-management
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird-signal
  namespace: netbird
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: stepca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbird-signal.practice.local
      secretName: netbird-signal-tls
  rules:
    - host: netbird-signal.practice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird-signal
                port:
                  number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbird-dashboard-cert
  namespace: netbird
spec:
  secretName: netbird-dashboard-tls
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-issuer
  dnsNames:
    - netbird.practice.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbird-api-cert
  namespace: netbird
spec:
  secretName: netbird-api-tls
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-issuer
  dnsNames:
    - netbird-api.practice.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbird-signal-cert
  namespace: netbird
spec:
  secretName: netbird-signal-tls
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-issuer
  dnsNames:
    - netbird-signal.practice.local
