# ArgoCD "App of Apps" - HomePractice Environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jefflouisma/homelab.git
    targetRevision: HEAD
    path: homepractice/apps
    directory:
      recurse: false
      exclude: 'argocd-root.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
