apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: "25.2.6"
    helm:
      values: |
        image:
          registry: quay.io
          repository: keycloak/keycloak
          tag: "26.4.7"

        auth:
          adminUser: admin
          existingSecret: keycloak-admin-secret
          passwordSecretKey: admin-password

        proxy: edge
        httpRelativePath: /

        production: false

        service:
          type: LoadBalancer
          loadBalancerIP: 10.10.10.210
          ports:
            http: 80
            https: 443

        postgresql:
          enabled: false

        externalDatabase:
          host: identity-postgres-postgresql.identity.svc.cluster.local
          port: 5432
          user: keycloak
          database: keycloak
          existingSecret: identity-postgres-secret
          existingSecretPasswordKey: keycloak-password

        replicaCount: 1

        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi

        extraEnvVars:
          - name: KC_PROXY
            value: "edge"
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_METRICS_ENABLED
            value: "true"
          - name: KC_HOSTNAME
            value: "keycloak.practice.local"

        extraVolumes:
          - name: realm-import
            configMap:
              name: keycloak-realm-config
              optional: true

        extraVolumeMounts:
          - name: realm-import
            mountPath: /opt/keycloak/data/import
            readOnly: true

  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
