apiVersion: v1
kind: ConfigMap
metadata:
  name: midpoint-config
  namespace: identity
data:
  config.xml: |
    <?xml version="1.0"?>
    <configuration>
        <midpoint>
            <repository>
                <type>native</type>
                <database>postgresql</database>
                <jdbcUrl>jdbc:postgresql://identity-postgres-postgresql.identity.svc.cluster.local:5432/midpoint</jdbcUrl>
                <jdbcUsername>midpoint</jdbcUsername>
            </repository>
            <audit>
                <auditService>
                    <auditServiceFactoryClass>com.evolveum.midpoint.audit.impl.LoggerAuditServiceFactory</auditServiceFactoryClass>
                </auditService>
                <auditService>
                    <auditServiceFactoryClass>com.evolveum.midpoint.repo.sqale.audit.SqaleAuditServiceFactory</auditServiceFactoryClass>
                </auditService>
            </audit>
        </midpoint>
    </configuration>
