apiVersion: v1
kind: Secret
metadata:
  name: freeipa-admin-secret
  namespace: identity
type: Opaque
stringData:
  admin-password: "FreeIPAAdmin2024!"
  ds-password: "DirectoryServer2024!"
  keycloak-ldap-password: "KeycloakLDAP2024!"
  midpoint-ldap-password: "MidPointLDAP2024!"
