apiVersion: v1
kind: Secret
metadata:
  name: identity-postgres-secret
  namespace: identity
type: Opaque
stringData:
  postgres-password: "IdentityPostgres2024!"
  keycloak-password: "KeycloakDB2024!"
  midpoint-password: "MidPointDB2024!"
