apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: caddy

resources:
  - deployment.yaml
  - step-ca-root-configmap.yaml
  - certificates.yaml

commonLabels:
  app.kubernetes.io/part-of: caddy
