apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-ca
  namespace: caddy
data:
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBizCCATGgAwIBAgIRALKeDB86/Me+c+3AIvHZ3eEwCgYIKoZIzj0EAwIwJDEi
    MCAGA1UEAxMZU3RlcCBDZXJ0aWZpY2F0ZXMgUm9vdCBDQTAeFw0yNTAxMDIxNzUz
    MTlaFw0zNTAxMDIxNzUzMTlaMCQxIjAgBgNVBAMTGVN0ZXAgQ2VydGlmaWNhdGVz
    IFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASeXm/MAbLWOCB2+Aue
    N8y5rAf8MrPV4VNiKLiVYv4sUKoJIWE6f4I/HJJbvffxJ1yQY8vy0D2JjMYffLIW
    hN1Do0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNV
    HQ4EFgQUC7Rtr3FZspbEW6tLY2b9aAgSmBgwCgYIKoZIzj0EAwIDSAAwRQIgH4jD
    Ua5rPSh0dXfKqGaJNxMU6vmTEGNeSYQ+qXQ51IQCIQDEo59WxO/4H+1wgCGGZmJw
    D5cAkPc4pIkEYKi1qJKPrg==
    -----END CERTIFICATE-----
