apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-ca
  namespace: caddy
data:
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBwzCCAWmgAwIBAgIQYa5KaQsAW9oBHZPLRkfNujAKBggqhkjOPQQDAjBAMRow
    GAYDVQQKExFTdGVwIENlcnRpZmljYXRlczEiMCAGA1UEAxMZU3RlcCBDZXJ0aWZp
    Y2F0ZXMgUm9vdCBDQTAeFw0yNTEyMjQyMzI4NTlaFw0zNTEyMjIyMzI4NTlaMEAx
    GjAYBgNVBAoTEVN0ZXAgQ2VydGlmaWNhdGVzMSIwIAYDVQQDExlTdGVwIENlcnRp
    ZmljYXRlcyBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFzdeEeDC
    fqPfptNmP0EWEBgLBb8Be42sFmwhfOAnTcolp6/ZZQRIKK3r9u2aP8dixAusyRIg
    M0ycD5nO9XLdFqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
    AQEwHQYDVR0OBBYEFJE6NJvsCLcMnKVyCQHmJj5ehsRDMAoGCCqGSM49BAMCA0gA
    MEUCIA4USqpEm+Z5gjauF+rV5AgIOgkHZ7pHWYUCKmrYS6pFAiEAgOxqpG2VnDyj
    zvL2kFIZsvrbc9g/AyTJ+K6WkJ9FqDI=
    -----END CERTIFICATE-----
