<?xml version="1.0"?>
<opnsense>
  <theme>opnsense</theme>
  <sysctl version="1.0.0">
    <item>
      <tunable>net.inet.ip.forwarding</tunable>
      <value>1</value>
      <descr>Enable IP forwarding</descr>
    </item>
  </sysctl>
  <system>
    <optimization>normal</optimization>
    <hostname>practice-opnsense</hostname>
    <domain>homelab.local</domain>
    <dnsallowoverride>1</dnsallowoverride>
    <dnsserver>8.8.8.8</dnsserver>
    <dnsserver>8.8.4.4</dnsserver>
    <group>
      <gid>1999</gid>
      <name>admins</name>
      <scope>system</scope>
      <description>System Administrators</description>
      <priv>page-all</priv>
      <member>0</member>
    </group>
    <user>
      <uid>0</uid>
      <name>root</name>
      <disabled>0</disabled>
      <scope>system</scope>
      <password>$2y$10$YRVoF4SgskIsrXOvOQjGieB9XqHPRra9R7d80B3BZdbY/j21TwBfS</password>
      <descr>System Administrator</descr>
      <apikeys>
        <item>
          <key>${api_key}</key>
          <secret>${api_secret_hash}</secret>
        </item>
      </apikeys>
    </user>
    <nextuid>2000</nextuid>
    <nextgid>2000</nextgid>
    <timezone>Etc/UTC</timezone>
    <timeservers>0.opnsense.pool.ntp.org 1.opnsense.pool.ntp.org</timeservers>
    <webgui>
      <protocol>https</protocol>
    </webgui>
    <disablenatreflection>yes</disablenatreflection>
    <usevirtualterminal>1</usevirtualterminal>
    <ipv6allow>1</ipv6allow>
    <ssh>
      <enabled>enabled</enabled>
      <group>admins</group>
      <permitrootlogin>1</permitrootlogin>
      <passwordauth>1</passwordauth>
    </ssh>
  </system>
  <interfaces>
    <wan>
      <enable>1</enable>
      <if>vtnet0</if>
      <descr>WAN</descr>
      <ipaddr>${wan_ip}</ipaddr>
      <subnet>${wan_subnet}</subnet>
      <gateway>WAN_GW</gateway>
    </wan>
    <lan>
      <enable>1</enable>
      <if>vtnet1</if>
      <descr>LAN</descr>
      <ipaddr>${lan_ip}</ipaddr>
      <subnet>${lan_subnet}</subnet>
    </lan>
    <lo0>
      <internal_dynamic>1</internal_dynamic>
      <descr>Loopback</descr>
      <enable>1</enable>
      <if>lo0</if>
      <ipaddr>127.0.0.1</ipaddr>
      <subnet>8</subnet>
    </lo0>
  </interfaces>
  <gateways>
    <gateway_item>
      <interface>wan</interface>
      <gateway>${wan_gateway}</gateway>
      <name>WAN_GW</name>
      <priority>255</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <descr>WAN Gateway</descr>
      <defaultgw>1</defaultgw>
    </gateway_item>
  </gateways>
  <nat>
    <outbound>
      <mode>automatic</mode>
    </outbound>
  </nat>
  <filter>
    <rule>
      <type>pass</type>
      <ipprotocol>inet</ipprotocol>
      <descr>Allow LAN to any</descr>
      <interface>lan</interface>
      <source>
        <network>lan</network>
      </source>
      <destination>
        <any/>
      </destination>
    </rule>
    <rule>
      <type>pass</type>
      <ipprotocol>inet</ipprotocol>
      <descr>Allow WAN management from home network</descr>
      <interface>wan</interface>
      <protocol>tcp</protocol>
      <source>
        <network>${management_network}</network>
      </source>
      <destination>
        <network>(self)</network>
        <port>22,443</port>
      </destination>
    </rule>
  </filter>
  <rrd>
    <enable/>
  </rrd>
  <revision>
    <username>terraform</username>
    <time>1700000000</time>
    <description>IaC initial configuration with API key</description>
  </revision>
</opnsense>
