apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: identity
data:
  homelab-realm.json: |
    {
      "realm": "homelab",
      "enabled": true,
      "displayName": "HomeLab Identity",
      "sslRequired": "external",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 5,
      "clients": [
        {
          "clientId": "midpoint",
          "name": "MidPoint IGA",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "redirectUris": ["https://midpoint.practice.local/*", "https://10.10.10.211/*"],
          "webOrigins": ["https://midpoint.practice.local", "https://10.10.10.211"]
        },
        {
          "clientId": "argocd",
          "name": "ArgoCD",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "redirectUris": ["https://10.10.10.200/*"],
          "webOrigins": ["https://10.10.10.200"]
        }
      ]
    }
