apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa-env
  namespace: identity
data:
  IPA_SERVER_HOSTNAME: "ipa.practice.local"
  IPA_SERVER_INSTALL_OPTIONS: >-
    --realm=PRACTICE.LOCAL
    --domain=practice.local
    --ds-password=DirectoryServer2024!
    --admin-password=FreeIPAAdmin2024!
    --unattended
    --no-ntp
    --no-ui-redirect
    --setup-dns
    --forwarder=10.10.10.1
    --no-dnssec-validation
