---
# HomeProd Environment Variables

# Network Configuration (direct LAN, no OPNsense)
k3s_ip: "192.168.1.50"
gateway: "192.168.1.254"

# K3s Configuration
k3s_version: "v1.33.6+k3s1"
k3s_disable:
  - traefik
  - servicelb
  - flannel
  - network-policy
  - kube-proxy

# MetalLB IP Range
metallb_ip_range: "192.168.1.60-192.168.1.70"
