apiVersion: v1
kind: ConfigMap
metadata:
  name: netbird-management-config
  namespace: netbird
data:
  management.json: |
    {
      "Stuns": [
        {
          "Proto": "udp",
          "URI": "stun:turn.practice.local:3478"
        }
      ],
      "TURNConfig": {
        "Turns": [
          {
            "Proto": "udp",
            "URI": "turn:turn.practice.local:3478",
            "Username": "netbird",
            "Password": null
          }
        ],
        "TimeBasedCredentials": false
      },
      "Signal": {
        "Proto": "https",
        "URI": "netbird-signal.practice.local:443"
      },
      "Datadir": "/var/lib/netbird/",
      "HttpConfig": {
        "Address": "0.0.0.0:8080",
        "AuthIssuer": "https://keycloak.practice.local/realms/practice",
        "AuthAudience": "netbird",
        "AuthKeysLocation": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/certs",
        "OIDCConfigEndpoint": "https://keycloak.practice.local/realms/practice/.well-known/openid-configuration"
      },
      "IdpManagerConfig": {
        "ManagerType": "keycloak",
        "ClientConfig": {
          "Issuer": "https://keycloak.practice.local/realms/practice",
          "TokenEndpoint": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/token",
          "ClientID": "netbird-backend",
          "GrantType": "client_credentials"
        },
        "ExtraConfig": {
          "AdminEndpoint": "https://keycloak.practice.local/admin/realms/practice"
        }
      },
      "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
          "Audience": "netbird",
          "AuthorizationEndpoint": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/auth",
          "TokenEndpoint": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/token",
          "ClientID": "netbird-client",
          "Scope": "openid profile email offline_access",
          "UseIDToken": false,
          "RedirectURLs": ["urn:ietf:wg:oauth:2.0:oob"]
        }
      },
      "PKCEAuthorizationFlow": {
        "ProviderConfig": {
          "Audience": "netbird",
          "AuthorizationEndpoint": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/auth",
          "TokenEndpoint": "https://keycloak.practice.local/realms/practice/protocol/openid-connect/token",
          "ClientID": "netbird-client",
          "Scope": "openid profile email offline_access",
          "UseIDToken": false,
          "RedirectURLs": ["http://localhost:53000"]
        }
      }
    }
